### PR TITLE
Improve group reordering

### PR DESCRIPTION
**Pull request by chhaymenghong**

### CODE REVIEW

**Comment by chhaymenghong** [comment]
yeah you can.

**Comment by shakeh** [comment]
Maybe we can talk about it offline but I’m using chrome

**Comment by dlamoris** [comment]
there's this "sweet" spot that's extremely hard to find if you want to move into an empty group, compared to moving a view under an empty view in the doc reorder, there's no "empty space" under an empty group to trigger the highlight

**Comment by shakeh** [comment]
thanks @chhaymenghong ! looks good

**Pull request merged**
