### PR TITLE
https://cae-jira.jpl.nasa.gov/browse/VE-885

### PR DESCRIPTION
**Pull request by chhaymenghong**

### CODE REVIEW

**Comment by chhaymenghong** [comment]
@dlamoris yeah it should be its own route. It would simplify codes in general, but let's not make it a part of this pr. We should just split it in the during the migration.
Also good catch on the "full doc controller" part. I will add a fix for that.

**Comment by shakeh** [comment]
I think @ellenvanwyk wants the breadcrumbs to change as well. Gives the user the wrong impression of where they are. also, @ellenvanwyk do you want to style the close differently?

**Comment by ellenvanwyk** [comment]
Let's leave the breadcrumbs as they are now.

**Comment by chhaymenghong** [comment]
cool. then this should be ready for merging

**Pull request merged**
