### PR TITLE
add a better formatted calendar picker ( VE-1067 )

### PR DESCRIPTION
**Pull request by chhaymenghong**

### CODE REVIEW

**Comment by dlamoris** [comment]
This pull request **introduces 8 alerts** when merging 35e2db350b61bebf52e042689df75985d69257de into 84aa7215277dc93b333c30db30b036726ffd3680 - [view on LGTM.com](https://lgtm.com/projects/g/Open-MBEE/ve/rev/pr-729b74333a9883269f6af388143008787b8077c3)

**new alerts:**

* 5 for Comparison between inconvertible types
* 3 for Useless conditional

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by dlamoris** [comment]
This pull request **introduces 8 alerts** when merging 78b8d7d2cd1ee66e09d3a742e6769a1967e63307 into 84aa7215277dc93b333c30db30b036726ffd3680 - [view on LGTM.com](https://lgtm.com/projects/g/Open-MBEE/ve/rev/pr-0164a13d08a818e620410c00241050a836529f85)

**new alerts:**

* 5 for Comparison between inconvertible types
* 3 for Useless conditional

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by shakeh** [comment]
@chhaymenghong this looks great but can you disallow selection of dates in the future?

**Comment by chhaymenghong** [comment]
@shakeh absolutely! coming right up

**Comment by dlamoris** [comment]
This pull request **introduces 8 alerts** when merging df995bbe85f0640d4122ea277e59beff07bc4e46 into 1441d6a47526657a3ded8223995ac1926980cfcc - [view on LGTM.com](https://lgtm.com/projects/g/Open-MBEE/ve/rev/pr-3eb24b62a8da02b50cb2eefa5c552d1a8cf04b9d)

**new alerts:**

* 5 for Comparison between inconvertible types
* 3 for Useless conditional

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Pull request merged**
